// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: replication.proto

#include "replication.pb.h"
#include "replication.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace replication {

static const char* Replication_method_names[] = {
  "/replication.Replication/AppendEntries",
  "/replication.Replication/Heartbeat",
};

std::unique_ptr< Replication::Stub> Replication::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Replication::Stub> stub(new Replication::Stub(channel, options));
  return stub;
}

Replication::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AppendEntries_(Replication_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Heartbeat_(Replication_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Replication::Stub::AppendEntries(::grpc::ClientContext* context, const ::replication::AppendRequest& request, ::replication::AppendReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::replication::AppendRequest, ::replication::AppendReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AppendEntries_, context, request, response);
}

void Replication::Stub::async::AppendEntries(::grpc::ClientContext* context, const ::replication::AppendRequest* request, ::replication::AppendReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::replication::AppendRequest, ::replication::AppendReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AppendEntries_, context, request, response, std::move(f));
}

void Replication::Stub::async::AppendEntries(::grpc::ClientContext* context, const ::replication::AppendRequest* request, ::replication::AppendReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AppendEntries_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::replication::AppendReply>* Replication::Stub::PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::replication::AppendRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::replication::AppendReply, ::replication::AppendRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AppendEntries_, context, request);
}

::grpc::ClientAsyncResponseReader< ::replication::AppendReply>* Replication::Stub::AsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::replication::AppendRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAppendEntriesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Replication::Stub::Heartbeat(::grpc::ClientContext* context, const ::replication::HeartbeatRequest& request, ::replication::HeartbeatReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::replication::HeartbeatRequest, ::replication::HeartbeatReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Heartbeat_, context, request, response);
}

void Replication::Stub::async::Heartbeat(::grpc::ClientContext* context, const ::replication::HeartbeatRequest* request, ::replication::HeartbeatReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::replication::HeartbeatRequest, ::replication::HeartbeatReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Heartbeat_, context, request, response, std::move(f));
}

void Replication::Stub::async::Heartbeat(::grpc::ClientContext* context, const ::replication::HeartbeatRequest* request, ::replication::HeartbeatReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Heartbeat_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::replication::HeartbeatReply>* Replication::Stub::PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::replication::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::replication::HeartbeatReply, ::replication::HeartbeatRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Heartbeat_, context, request);
}

::grpc::ClientAsyncResponseReader< ::replication::HeartbeatReply>* Replication::Stub::AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::replication::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHeartbeatRaw(context, request, cq);
  result->StartCall();
  return result;
}

Replication::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Replication_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Replication::Service, ::replication::AppendRequest, ::replication::AppendReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Replication::Service* service,
             ::grpc::ServerContext* ctx,
             const ::replication::AppendRequest* req,
             ::replication::AppendReply* resp) {
               return service->AppendEntries(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Replication_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Replication::Service, ::replication::HeartbeatRequest, ::replication::HeartbeatReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Replication::Service* service,
             ::grpc::ServerContext* ctx,
             const ::replication::HeartbeatRequest* req,
             ::replication::HeartbeatReply* resp) {
               return service->Heartbeat(ctx, req, resp);
             }, this)));
}

Replication::Service::~Service() {
}

::grpc::Status Replication::Service::AppendEntries(::grpc::ServerContext* context, const ::replication::AppendRequest* request, ::replication::AppendReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Replication::Service::Heartbeat(::grpc::ServerContext* context, const ::replication::HeartbeatRequest* request, ::replication::HeartbeatReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace replication

